name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-build-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm run verify-deps
    - name: Lint code
      run: pnpm run lint
    - name: Test smoke
      run: pnpm run build
    - name: Test unit
      run: pnpm run test:unit
    - name: Test E2E (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run -a pnpm run test:e2e
    - name: Test E2E (non-Linux)
      if: runner.os != 'Linux'
      run: pnpm run test:e2e
