name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
    - name: Install Dependencies
      run: pnpm run verify-deps
    - name: Lint Code
      run: pnpm run lint
    - name: Test Typings
      run: pnpm run test:typings
    - name: Test Unit
      run: pnpm run test:unit
    - name: Test E2E (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run -a pnpm run test:e2e
    - name: Test E2E (non-Linux)
      if: runner.os != 'Linux'
      run: pnpm run test:e2e
