name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-code:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 9
    - name: Install Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 20.x
        cache: 'pnpm'
    - name: Install Dependencies
      run: npx npm-run-all -l verify-deps:*
    - name: Lint Code
      run: pnpm run lint
    - name: Test Typings
      run: pnpm run test:typings
