name: Commit linting
on:
  pull_request:
    branches: [ main ]

jobs:
  lint-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
