name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - uses: pnpm/action-setup@v5
      with:
        version: latest

    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 24.x

    - name: Cache node_modules
      uses: actions/cache@v5
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml', 'pnpm-workspace.yaml') }}

    - name: Install Dependencies
      run: npx npm-run-all -l verify-deps:*

    - name: Build
      run: pnpm run build

    - name: Test E2E (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run -a pnpm test:e2e

    - name: Test E2E (non-Linux)
      if: runner.os != 'Linux'
      run: pnpm test:e2e

    - name: Upload failed test recordings
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: e2e-test-recordings-${{ matrix.os }}
        path: node_modules/.wdio-video
